baseURL = 'https://andykhv.github.io/'
languageCode = 'en-us'
title = 'Andy Khov'
theme = 'devise'
enableEmoji = true
copyright = "&copy; Copyright 2025, Andy Khov"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = -110
  [[menu.main]]
    identifier = "personal"
    name = "Personal"
    title = "Personal"
    url = "/personal"
    weight = -110
  [[menu.main]]
    identifier = "tech"
    name = "Tech"
    title = "Tech"
    url = "/tech"
    weight = -110


# Configuration Features
[params]
  description = "Andy Khov's Blog"
  header_title = "Andy Khov"
  home_image = "/avatar.jpg"
  header_subtitle = ""
  recent_posts = 10
  mainSections = ["personal", "tech"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "https://github.com/andykhv"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/andykhov/"
  [[params.social]]
    fa_icon = "fab fa-mastodon fa-1x"
    href = "https://hachyderm.io/@andykhov"
