baseURL = 'https://andykhv.github.io/'
languageCode = 'en-us'
title = 'Andy Khov'
theme = 'devise'
enableEmoji = true
copyright = "&copy; Copyright 2023, Andy Khov"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

# Configuration Features
[params]
  description = "Andy Khov's Blog"
  header_title = "Andy Khov"
  header_subtitle = "In the never ending cycle of learning"
  recent_posts = 5
  mainSections = ["personal"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "https://github.com/andykhv"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/andykhov/"
